### ISSUE TITLE
Run/monitor xvfb-run

### ISSUE THREAD

**Issue by drnic** [engineyard/eycloud-app-jenkins#3]
Jesse, if xvfb-run works a treat as per http://holloway.co.nz/docvert/xvfb-run.txt if you've got time, could you include it in the cookbooks here?

Thanks mate,
Nic

/cc @jc00ke

**Comment by jc00ke** [comment]
I love that you assigned this to me :smile:

Updates were made in 70da465
Can you please give it a try and let me know?

**Comment by drnic** [comment]
Yeah, it amused me at the time too :)

Trying it now!

**Comment by drnic** [comment]
chef error when I deployed:

```
~> running deploy hook: deploy/before_migrate.rb
[Thu, 22 Mar 2012 23:12:54 +0000] INFO: Starting Chef Solo Run
[Thu, 22 Mar 2012 23:12:57 +0000] INFO: Ran execute[reporting for Installing SM framework] successfully
[Thu, 22 Mar 2012 23:12:58 +0000] INFO: Ran execute[install-sm] successfully
[Thu, 22 Mar 2012 23:12:58 +0000] INFO: Ran execute[sm ext install eyapi /data/jenkins/releases/20120322231245/deploy/cookbooks/eyapi/repo] successfully
[Thu, 22 Mar 2012 23:12:58 +0000] INFO: Ran execute[sm ext install jenkins /data/jenkins/releases/20120322231245/deploy/cookbooks/jenkins/repo] successfully
[Thu, 22 Mar 2012 23:12:59 +0000] INFO: Ran execute[sm jenkins install] successfully
[Thu, 22 Mar 2012 23:13:01 +0000] INFO: Ran execute[sm jenkins configure] successfully
[Thu, 22 Mar 2012 23:13:02 +0000] INFO: Ran execute[sm jenkins restart] successfully
[Thu, 22 Mar 2012 23:13:14 +0000] ERROR: template[/engineyard/bin/xvfb-run] (/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/recipe.rb line 187) had an error:
Cannot find a preferred file for xvfb-run.erb!
/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/mixin/find_preferred_file.rb:91:in `find_preferred_file'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/provider/template.rb:47:in `action_create'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/runner.rb:87:in `send'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/runner.rb:87:in `converge'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/runner.rb:85:in `each'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/runner.rb:85:in `converge'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/resource_collection.rb:58:in `each'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/resource_collection.rb:57:in `each'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/runner.rb:63:in `converge'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/client.rb:348:in `converge'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/lib/chef/client.rb:96:in `run_solo'/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/chef-0.6.0.2/bin/chef-solo:94/usr/local/ey_resin/ruby/bin/chef-solo:19:in `load'/usr/local/ey_resin/ruby/bin/chef-solo:19
```

**Comment by drnic** [comment]
Going to bump to chef 0.10 as a starter.

**Comment by drnic** [comment]
Ok, fixed now.

**Comment by drnic** [comment]
Thanks mate!

**Comment by jc00ke** [comment]
You're welcome!
