### ISSUE TITLE
STDERR: sh: ey-enzyme: command not found

### ISSUE THREAD

**Issue by emachnic** [engineyard/eycloud-app-jenkins#5]
@zdennis reported this issue and I've had the same problem getting it up and running. Bundler seems to install everything fine and the deploy just blows up looking for `ey-enzyme`

Relevant backlog:

Unpacking common recipe into cookbooks from /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks
[Mon, 09 Apr 2012 09:10:11 -0700] INFO: **\* Chef 0.10.8 ***
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Setting the run_list to "recipe[main]" from JSON
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Run List is [recipe[main]]
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Run List expands to [main]
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Starting Chef Run for i-cdb2c7ae
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Running start handlers
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Start handlers complete.
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Processing execute[reporting for Installing SM framework] action run (sm::install line 2)
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: execute[reporting for Installing SM framework] sh(ey-enzyme --report '')
[Mon, 09 Apr 2012 09:10:13 -0700] ERROR: execute[reporting for Installing SM framework](sm::install line 2) had an error: Expected process to exit with [0], but received '127'
---- Begin output of ey-enzyme --report '' ----
STDOUT: 
STDERR: sh: ey-enzyme: command not found
---- End output of ey-enzyme --report '' ----
Ran ey-enzyme --report '' returned 127
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: Processing execute[install-sm] action run (sm::install line 3)
[Mon, 09 Apr 2012 09:10:13 -0700] INFO: execute[install-sm] sh(  for entry in /tmp/sm-\* ; do rm -rf ${entry} ; done

  curl -L -s https://github.com/sm/sm/tarball/master -o sm-master.tar.gz && 
  tar zxf sm-master.tar.gz && # unpack
  mv sm-sm-\* sm-master &&     # rename github-named folder to something known
  cd sm-master && 
  ./install # >/dev/null

  # prefix_path=/eystack ./install >/dev/null
)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[install-sm] ran successfully
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: Processing link[/bin/sm] action create (sm::install line 19)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: link[/bin/sm] created
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: Processing execute[sm ext install eyapi /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/eyapi/repo] action run (eyapi::install_sm_ext line 6)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[sm ext install eyapi /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/eyapi/repo] sh(sm ext install eyapi /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/eyapi/repo)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[sm ext install eyapi /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/eyapi/repo] ran successfully
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: Processing execute[sm ext install jenkins /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/jenkins/repo] action run (jenkins::install_sm_ext line 6)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[sm ext install jenkins /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/jenkins/repo] sh(sm ext install jenkins /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/jenkins/repo)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[sm ext install jenkins /data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/jenkins/repo] ran successfully
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: Processing execute[sm jenkins install] action run (jenkins::install line 6)
[Mon, 09 Apr 2012 09:10:15 -0700] INFO: execute[sm jenkins install] sh(sm jenkins install)
[Mon, 09 Apr 2012 09:10:17 -0700] INFO: execute[sm jenkins install] ran successfully
[Mon, 09 Apr 2012 09:10:17 -0700] INFO: Processing execute[sm jenkins configure] action run (jenkins::configure line 6)
[Mon, 09 Apr 2012 09:10:17 -0700] INFO: execute[sm jenkins configure] sh(sm jenkins configure)
[Mon, 09 Apr 2012 09:10:18 -0700] ERROR: execute[sm jenkins configure](jenkins::configure line 6) has had an error
[Mon, 09 Apr 2012 09:10:18 -0700] ERROR: execute[sm jenkins configure](/data/eycloudappjenkins/releases/20120409160930/deploy/cookbooks/jenkins/recipes/configure.rb:6:in `from_file') had an error:
execute[sm jenkins configure](jenkins::configure line 6) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of sm jenkins configure ----
STDOUT: 
STDERR: Can't locate object method "qv" via package "version" at /opt/sm/core/internal/perl/version.pm line 150.
Compilation failed in require at /opt/sm/bin/sm-mustache line 79.
BEGIN failed--compilation aborted at /opt/sm/bin/sm-mustache line 79.
ERROR(log): There was an error rendering the template!
---- End output of sm jenkins configure ----
Ran sm jenkins configure returned 1
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:206:in `invalid!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:192:in`error!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/provider/execute.rb:58:in`action_run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource.rb:440:in `run_action'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:45:in`run_action'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in`each'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block in converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:94:in`block in execute_each_resource'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:92:in`execute_each_resource'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:76:in `converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:312:in`converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:160:in `run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:192:in`block in run_application'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `loop'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in`run_application'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application.rb:67:in `run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/bin/chef-solo:25:in`<top (required)>'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/bin/chef-solo:19:in `load'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/bin/chef-solo:19:in`<main>'
[Mon, 09 Apr 2012 09:10:18 -0700] ERROR: Running exception handlers
[Mon, 09 Apr 2012 09:10:18 -0700] ERROR: Exception handlers complete
[Mon, 09 Apr 2012 09:10:18 -0700] FATAL: Stacktrace dumped to /data/eycloudappjenkins/releases/20120409160930/deploy/chef-stacktrace.out
[Mon, 09 Apr 2012 09:10:18 -0700] FATAL: Chef::Exceptions::ShellCommandFailed: execute[sm jenkins configure](jenkins::configure line 6) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of sm jenkins configure ----
STDOUT: 
STDERR: Can't locate object method "qv" via package "version" at /opt/sm/core/internal/perl/version.pm line 150.
Compilation failed in require at /opt/sm/bin/sm-mustache line 79.
BEGIN failed--compilation aborted at /opt/sm/bin/sm-mustache line 79.
ERROR(log): There was an error rendering the template!
---- End output of sm jenkins configure ----
Ran sm jenkins configure returned 1
Generated at 2012-04-09 09:10:18 -0700
Chef::Exceptions::ShellCommandFailed: execute[sm jenkins configure](jenkins::configure line 6) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of sm jenkins configure ----
STDOUT: 
STDERR: Can't locate object method "qv" via package "version" at /opt/sm/core/internal/perl/version.pm line 150.
Compilation failed in require at /opt/sm/bin/sm-mustache line 79.
BEGIN failed--compilation aborted at /opt/sm/bin/sm-mustache line 79.
ERROR(log): There was an error rendering the template!
---- End output of sm jenkins configure ----
Ran sm jenkins configure returned 1
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:206:in `invalid!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/shell_out.rb:192:in`error!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/provider/execute.rb:58:in`action_run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource.rb:440:in `run_action'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:45:in`run_action'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in`each'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:81:in `block in converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:94:in`block in execute_each_resource'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/resource_collection.rb:92:in`execute_each_resource'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/runner.rb:76:in `converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:312:in`converge'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:160:in `run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:192:in`block in run_application'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in `loop'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:183:in`run_application'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application.rb:67:in `run'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/gems/chef-0.10.8/bin/chef-solo:25:in`<top (required)>'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/bin/chef-solo:19:in `load'
/data/eycloudappjenkins/shared/bundled_gems/ruby/1.9.1/bin/chef-solo:19:in`<main>'+ 0m 50s ~> Symlinking code.

**Comment by joshuap** [comment]
+1 on this. Any ideas? ey-enzyme is in the path both for the deploy user and after doing `sudo -i`, but calling `sudo which ey-enzyme` from the deploy user's account results in:

which: no ey-enzyme in (/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin)
