### ISSUE TITLE
Deploy runs fail with missing `generate` method on JSON.

### ISSUE THREAD

**Issue by benschwarz** [engineyard/eycloud-app-jenkins#6]
Deploys are failing, here is the output: (Deployed from HEAD)

```
/usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/engineyard-serverside/deploy_hook.rb:21:in `run': undefined method `generate' for #<JSON::Ext::Generator::State:0x8396eb4> (NoMethodError)
    from (eval):6:in `run'
    from (eval):5:in `open'
    from (eval):5:in `run'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/engineyard-serverside/deploy_hook.rb:15:in `chdir'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/engineyard-serverside/deploy_hook.rb:15:in `run'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/engineyard-serverside/cli.rb:89:in `hook'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/task.rb:33:in `send'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/task.rb:33:in `run'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/invocation.rb:109:in `invoke'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/invocation.rb:116:in `call'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/invocation.rb:116:in `invoke'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor.rb:137:in `start'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor/base.rb:378:in `start'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/lib/vendor/thor/lib/thor.rb:124:in `start'
    from /usr/local/ey_resin/ruby/lib/ruby/gems/1.8/gems/engineyard-serverside-1.6.4/bin/engineyard-serverside:10
```

**Comment by benschwarz** [comment]
ping @drnic

**Comment by drnic** [comment]
Hmm, I just ran through the README and it created Jenkins successfully. I used Stack v2. I'll do it again with Stack v1 and see if issue appears.

**Comment by benschwarz** [comment]
Whats stack v1?

**Comment by drnic** [comment]
Taking kids to school (and end of year school breakfast). Back in an hour or so. 

We started shipping newer base AMIs.

**Comment by drnic** [comment]
Email me your account details and I'll look at what you have/had.

**Comment by drnic** [comment]
Confirmed that it worked on Stack v1. 

@benschwarz tweeted http://twitter.com/benschwarz/status/208558353046175744

"I was using the 'rezeko' account, not sure if that helps you… ?  I ended up using other scripts ey had on their GH account"

Ben, what does " I ended up using other scripts ey had on their GH account" mean?

**Comment by drnic** [comment]
Mate, can you try the following; if it works I'll update the documentation:

```
gem install ey_cli
ey_cli create_app --git git://github.com/engineyard/eycloud-app-jenkins.git --name jenkins --env_name jenkins --solo
```

**Comment by drnic** [comment]
Correction: use rack

```
ey_cli create_app --git git://github.com/engineyard/eycloud-app-jenkins.git --name jenkins --env_name jenkins --solo --type rack
```

**Comment by drnic** [comment]
README is updated. Also how to setup DNS.
